import Navbar from '@/components/NavBar';

export const metadata = {
    title: {
        default: 'Next.dev',
        template: ' - Nextjs.dev - %s',
    },
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="ko">
            <body>
                <header>
                    <h1>===Header===</h1>
                    <Navbar />
                </header>
                <main>{children}</main>
                <footer>
                    <h2>---Footer---</h2>
                </footer>
            </body>
        </html>
    );
}
